theory:
  classy:
    extra_args:
      N_ncdm: 1
      N_ur: 2.0328
      output: tCl,pCl,lCl,mPk
      P_k_max_h/Mpc: 10.0
      lensing: 'yes'
      f_idm: 0.0035
      N_idr: 0.05
      a_idm_dr: 47612.96
      nindex_idm_dr: 4
      idr_nature: free_streaming
likelihood:
  planck_2018_lowl.TT: null
  planck_2018_lowl.EE: null
  planck_2018_highl_plik.TTTEEE_lite_native: null
  bao.desi_dr2: null
  sn.pantheonplus: null
params:
  omega_b:
    prior:
      min: 0.02
      max: 0.0245
    ref:
      dist: norm
      loc: 0.02237
      scale: 0.0001
    proposal: 0.0001
    latex: \Omega_b h^2
  omega_cdm:
    prior:
      min: 0.1
      max: 0.14
    ref:
      dist: norm
      loc: 0.12
      scale: 0.001
    proposal: 0.0005
    latex: \Omega_{cdm} h^2
  H0:
    prior:
      min: 55.0
      max: 85.0
    ref:
      dist: norm
      loc: 67.4
      scale: 0.5
    proposal: 0.3
    latex: H_0
  tau_reio:
    prior:
      min: 0.01
      max: 0.12
    ref:
      dist: norm
      loc: 0.054
      scale: 0.006
    proposal: 0.003
    latex: \tau
  logA:
    prior:
      min: 2.8
      max: 3.3
    ref:
      dist: norm
      loc: 3.044
      scale: 0.01
    proposal: 0.005
    latex: \ln(10^{10}A_s)
    drop: true
  A_s:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_s
  n_s:
    prior:
      min: 0.9
      max: 1.05
    ref:
      dist: norm
      loc: 0.965
      scale: 0.004
    proposal: 0.002
    latex: n_s
  m_ncdm:
    value: 0.06
    renames: mnu
  Omega_m:
    latex: \Omega_m
  sigma8:
    latex: \sigma_8
  S8:
    derived: 'lambda sigma8, Omega_m: sigma8*(Omega_m/0.3)**0.5'
    latex: S_8
  rs_drag:
    latex: r_{drag}
  age:
    latex: Age/Gyr
  A_planck:
    prior:
      dist: norm
      loc: 1.0
      scale: 0.0025
    ref:
      dist: norm
      loc: 1.0
      scale: 0.002
    proposal: 0.0005
    latex: A_{Planck}
